# Build Stage
FROM node:18-alpine AS builder

WORKDIR /app

RUN apk add --no-cache openssl1.1-compat

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install
RUN npx prisma generate

COPY . .

RUN npm run build

# Production Stage
FROM node:18-alpine

WORKDIR /app

RUN apk add --no-cache openssl1.1-compat

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/prisma ./prisma

EXPOSE 5000

CMD ["node", "dist/index.js"]
